# ===============================
# SPRING CONFIG
# ===============================
spring.application.name=estore

# ===============================
# SERVER PATH
# ===============================
server.servlet.context-path=/api

# ===============================
# SPRING DOC
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
